const {test}=require('node:test'); const assert=require('node:assert/strict'); const fs=require('node:fs'); const vm=require('node:vm'); const path=require('node:path');
const file=path.resolve(__dirname,'../../main/assets/device/seed-android.js');
function setup(timers={setTimeout,clearTimeout}){let sent=[],events={};let w={seed:{helper:42},seedDeviceTransport:{postMessage(s){sent.push(JSON.parse(s));}},addEventListener(n,f){events[n]=f;}};w.window=w;vm.runInNewContext(fs.existsSync(file)?fs.readFileSync(file,'utf8'):'', {window:w,setTimeout:timers.setTimeout,clearTimeout:timers.clearTimeout,TextEncoder});return {w,sent,events};}
test('SDK exists and preserves seed helpers',()=>{const {w}=setup();assert.equal(typeof w.seed.android?.call,'function');assert.equal(w.seed.helper,42);});
test('correlates versioned replies',async()=>{const {w,sent}=setup();const p=w.seed.android.call({method:'sensor.list',params:{}});assert.equal(sent[0].v,1);w.seedDeviceTransport.onmessage({data:JSON.stringify({v:1,id:sent[0].id,ok:true,result:{sensors:[]}})});assert.deepEqual(JSON.parse(JSON.stringify(await p)),{sensors:[]});});
test('busy and disposal reject',async()=>{const {w,events}=setup();const p=w.seed.android.call({method:'camera.capture',params:{}});await assert.rejects(w.seed.android.call({method:'sensor.list',params:{}}),{code:'BUSY'});events.pagehide();await assert.rejects(p,{code:'CANCELLED'});});
test('future methods forward without SDK schema edits',async(t)=>{const {w,sent,events}=setup();t.after(()=>events.pagehide());const p=w.seed.android.call({method:'device.future',params:{feature:{enabled:true},values:[1,2]}});p.catch(()=>{});assert.equal(sent.length,1);assert.deepEqual(sent[0],{v:1,id:sent[0].id,method:'device.future',params:{feature:{enabled:true},values:[1,2]}});w.seedDeviceTransport.onmessage({data:JSON.stringify({v:1,id:sent[0].id,ok:true,result:{future:true}})});assert.deepEqual(JSON.parse(JSON.stringify(await p)),{future:true});});
test('unknown methods forward and reject the native UNKNOWN_METHOD reply',async(t)=>{const {w,sent,events}=setup();t.after(()=>events.pagehide());const p=w.seed.android.call({method:'sensor.subscribe',params:{type:1}});p.catch(()=>{});assert.equal(sent.length,1);w.seedDeviceTransport.onmessage({data:JSON.stringify({v:1,id:sent[0].id,ok:false,error:{code:'UNKNOWN_METHOD',message:'Capability is not available'}})});await assert.rejects(p,{code:'UNKNOWN_METHOD'});});
test('invalid sensor parameters forward and reject the native INVALID_REQUEST reply',async(t)=>{const {w,sent,events}=setup();t.after(()=>events.pagehide());const p=w.seed.android.call({method:'sensor.read',params:{type:1.5,unexpected:true}});p.catch(()=>{});assert.equal(sent.length,1);assert.deepEqual(sent[0].params,{type:1.5,unexpected:true});w.seedDeviceTransport.onmessage({data:JSON.stringify({v:1,id:sent[0].id,ok:false,error:{code:'INVALID_REQUEST',message:'Invalid device capability request'}})});await assert.rejects(p,{code:'INVALID_REQUEST'});});
test('malformed generic envelopes reject locally',async(t)=>{const {w,sent,events}=setup({setTimeout(f){setImmediate(f);return 1;},clearTimeout(){}});t.after(()=>events.pagehide());for(const request of [null,[],{}, {method:'',params:{}},{method:' '.repeat(3),params:{}},{method:'m'.repeat(129),params:{}},{method:1,params:{}},{method:'sensor.list',params:null},{method:'sensor.list',params:[]},{method:'sensor.list',params:'bad'},{method:'sensor.list',params:{},extra:true},Object.create({method:'sensor.list',params:{}})]) await assert.rejects(w.seed.android.call(request),{code:'INVALID_REQUEST'});assert.equal(sent.length,0);});
test('UTF8 wire limit and unserializable parameters reject locally',async()=>{const {w,sent}=setup();const circular={};circular.self=circular;for(const params of [{value:'é'.repeat(4096)},circular,{value:1n}]) await assert.rejects(w.seed.android.call({method:'device.future',params}),{code:'INVALID_REQUEST'});assert.equal(sent.length,0);});
test('timeout rejects and releases the operation slot',async()=>{let fire;const {w,sent}=setup({setTimeout(f,ms){assert.equal(ms,125000);fire=f;return 1;},clearTimeout(){}});const p=w.seed.android.call({method:'sensor.list',params:{}});fire();await assert.rejects(p,{code:'TIMEOUT'});const next=w.seed.android.call({method:'sensor.list',params:{}});assert.notEqual(sent[0].id,sent[1].id);w.seedDeviceTransport.onmessage({data:JSON.stringify({v:1,id:sent[1].id,ok:true,result:{}})});await next;});
test('wrong IDs and versions never settle a promise',async()=>{const {w,sent}=setup();const p=w.seed.android.call({method:'sensor.list',params:{}});w.seedDeviceTransport.onmessage({data:JSON.stringify({v:1,id:'unknown',ok:true,result:{}})});w.seedDeviceTransport.onmessage({data:JSON.stringify({v:2,id:sent[0].id,ok:true,result:{}})});await assert.rejects(w.seed.android.call({method:'sensor.list',params:{}}),{code:'BUSY'});w.seedDeviceTransport.onmessage({data:JSON.stringify({v:1,id:sent[0].id,ok:true,result:{}})});await p;});
test('restored cached page resumes calls without reusing old request IDs',async(t)=>{
  const {w,sent,events}=setup(); t.after(()=>events.pagehide());
  const old=w.seed.android.call({method:'sensor.list',params:{}});
  events.pagehide(); await assert.rejects(old,{code:'CANCELLED'});
  await assert.rejects(w.seed.android.call({method:'sensor.list',params:{}}),{code:'CANCELLED'});
  assert.equal(typeof events.pageshow,'function'); events.pageshow({persisted:true});
  const current=w.seed.android.call({method:'sensor.list',params:{}}); current.catch(()=>{});
  assert.notEqual(sent[0].id,sent[1].id);
  w.seedDeviceTransport.onmessage({data:JSON.stringify({v:1,id:sent[0].id,ok:true,result:{stale:true}})});
  await assert.rejects(w.seed.android.call({method:'sensor.list',params:{}}),{code:'BUSY'});
  w.seedDeviceTransport.onmessage({data:JSON.stringify({v:1,id:sent[1].id,ok:true,result:{sensors:[]}})});
  assert.deepEqual(JSON.parse(JSON.stringify(await current)),{sensors:[]});
});
test('structured error and malformed messages',async()=>{const {w,sent}=setup();const p=w.seed.android.call({method:'sensor.list',params:{}});w.seedDeviceTransport.onmessage({data:new ArrayBuffer(4)});w.seedDeviceTransport.onmessage({data:JSON.stringify({v:1,id:sent[0].id,ok:false,error:{code:'PERMISSION_DENIED',message:'No'}})});await assert.rejects(p,{code:'PERMISSION_DENIED'});});
